from item import Item, Weapon, Treasure, Armor, Food, LightSource

excaliber = Weapon("Excaliber", "The Lady of the Lake, her arm clad in the purest shimmering samite, held aloft Excalibur from the bosom of the water signifying by Divine Providence that you, Arthur, were to carry Excalibur.", 10)
grenade = Weapon("Holy Hand Grenade of Antioch", "And Saint Attila raised the hand grenade up on high, saying, ‘O Lord, bless this thy hand grenade, that with it thou mayst blow thine enemies to tiny bits, in thy mercy.’ And the Lord did grin. And the people did feast upon the lambs and sloths, and carp and anchovies, and orangutans and breakfast cereals, and fruit-bats. And the Lord spake, saying, ‘First shalt thou take out the Holy Pin. Then shalt thou count to three, no more, no less. Three shall be the number thou shalt count, and the number of the counting shall be three. Four shalt thou not count, neither count thou two, excepting that thou then proceed to three. Five is right out. Once the number three, being the third number, be reached, then lobbest thou thy Holy Hand Grenade of Antioch towards thy foe, who, being naughty in my sight, shall snuff it.'  Amen.", 50)
rock = Item("Rock", "The solid mineral material forming part of the surface of the earth and other similar planets, exposed on the surface or underlying the soil or oceans.")
stick = Item("Stick", "A thin piece of wood that has fallen or been cut from a tree.")
coin = Treasure("Coin", "A single coin.", 1)
duck = Treasure('Duck', "If something weighs as much as a duck, it must be made of wood.", 10)
ninePence = Treasure("Pence", "Nine pence.  Enough to pay a mortician.", 9)
shrubbery = Treasure("Shrubbery", "It's...  a shrubbery!", 10)
elderberries = Treasure("Elderberries", "A very... *cough* manly... *cough* perfume...  *snicker snicker*", 10)
deed = Treasure("Deed", "A deed for HUGE...  tracts of land!", 10)
hamster = Item("Hamster", "This is your Mother.  Do not lose her.")
coconuts = Item("Coconuts", "A mighty steed!")
shield = Armor("Shield", "A worn, wooden shield.", 10)
spam1 = Food("Spam", "I would like some Spam.", 1)
spam2 = Food("SpamSpam", "I would like some Spam and Spam.", 2)
spam3 = Food("SpamSpamSpam", "I would like some Spam, Spam, and Spam", 3)
spam4 = Food("SpamSpamSpamSpam", "I would like some Spam, Spam, Spam, and Spam", 4)
spam5 = Food("SpamSpamSpamSpamSpam", "I would like some Spam, Spam, Spam, Spam, and Spam", 5)
eggs = Food("Eggs", "It's a tasty egg.", 1)
bacon = Food("Bacon", "What dreams are made of.", 10)
lantern = LightSource("Lantern", "A lantern that you can light with a fire source.", False)
torch = LightSource("Torch", "A branch with an oil soaked rag wrapped on one end.", False)
flint = Item("Flint", "You can use flint against a piece of metal to create fire.")
wagon = Item("Wagon", "Bring out'cher dead!")
deadPerson = Item("Body", "They're not so happy... =(")